name       : libxaw3d
version    : 1.6.3
release    : 6
source     :
    - http://xorg.freedesktop.org/archive/individual/lib/libXaw3d-1.6.3.tar.gz : 9f42b409e5a4a0d7a2c94595b31d17fc078e5e307d14389dbc396754c3a01fcc
homepage   : http://www.x.org
license    :
    - MIT
summary    : General-purpose replacement for the Athena toolkit.
component  : xorg.library
description: |
    Xaw3d is a general-purpose replacement for the Athena toolkit which adds a
    3D appearance and support for XPM images.
builddeps  :
    - pkgconfig32(xext)
    - pkgconfig32(xmu)
    - pkgconfig32(xt)
    - pkgconfig32(x11)
emul32     : yes
setup      : |
    %configure --prefix=/usr \
               --disable-static
build      : |
    %make
install    : |
    %make_install
