name        : libxaw3d
version     : 1.6
release     : 3
source      :
    - http://xorg.freedesktop.org/archive/individual/lib/libXaw3d-1.6.tar.gz : f543a141119028610523b80c5057252e079ef27469e5446fba35d02b2b608400
homepage    : http://www.x.org
license     :
    - MIT
summary     : General-purpose replacement for the Athena toolkit.
component   : xorg.library
builddeps   :
    - pkgconfig(xext)
    - pkgconfig32(xext)
    - pkgconfig(xmu)
    - pkgconfig32(xmu)
    - pkgconfig(xt)
    - pkgconfig32(xt)
    - pkgconfig(x11)
    - pkgconfig32(x11)
    - glibc-32bit-devel
    - libgcc-32bit
emul32      : yes
description : |
    Xaw3d is a general-purpose replacement for the Athena toolkit which adds a 3D appearance and support for XPM images.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
