name       : libxaw3d
version    : 1.6
release    : 4
source     :
    - http://xorg.freedesktop.org/archive/individual/lib/libXaw3d-1.6.tar.gz : f543a141119028610523b80c5057252e079ef27469e5446fba35d02b2b608400
homepage   : http://www.x.org
license    :
    - MIT
summary    : General-purpose replacement for the Athena toolkit.
component  : xorg.library
description: |
    Xaw3d is a general-purpose replacement for the Athena toolkit which adds a
    3D appearance and support for XPM images.
builddeps  :
    - pkgconfig32(xext)
    - pkgconfig32(xmu)
    - pkgconfig32(xt)
    - pkgconfig32(x11)
emul32     : yes
setup      : |
    %configure --prefix=/usr \
               --disable-static
build      : |
    %make
install    : |
    %make_install
